# Generated by Django 5.0.14 on 2025-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.CharField(max_length=50),
        ),
    ]
